/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */
import type {
  CreateAccessTokenRequest,
  RefreshTokenRequest,
  TokenResponse
} from '../../interfaces/api'
import { customInstance } from '../../api/api-interceptor';
import type { BodyType } from '../../api/api-interceptor';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  export const getAuthentication = () => {
/**
 * @summary Realiza autenticação do usuário com base nas credenciais fornecidas
 */
const autenticarOUsuário = (
    createAccessTokenRequest: BodyType<CreateAccessTokenRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TokenResponse>(
      {url: `/api/token/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccessTokenRequest
    },
      options);
    }
  /**
 * @summary Realiza autenticação do usuário com base no refresh token.
 */
const refreshToken = (
    refreshTokenRequest: BodyType<RefreshTokenRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TokenResponse>(
      {url: `/api/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest
    },
      options);
    }
  return {autenticarOUsuário,refreshToken}};
export type AutenticarOUsuárioResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthentication>['autenticarOUsuário']>>>
export type RefreshTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthentication>['refreshToken']>>>
