/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface CreateUserRequest {
  /** @nullable */
  confirmPassword?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  idAlternativo?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  personId?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  tenantsId?: string[] | null;
  /** @nullable */
  userName?: string | null;
}
