/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface CreateTenantRequest {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  issuer?: string | null;
  /** @nullable */
  name?: string | null;
  personId: string;
  /** @nullable */
  tenantGroupId: string | null;
}
