/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export type ListarPessoasParams = {
PageNumber?: number;
PageSize?: number;
SearchTerm?: string;
SortColumn?: string;
ReverseOrder?: boolean;
Enable?: boolean;
};
