/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */
import type { PersonResponse } from './personResponse';

export interface PersonResponseIPagedList {
  readonly hasNext?: boolean;
  readonly hasPrevious?: boolean;
  /** @nullable */
  readonly items?: readonly PersonResponse[] | null;
  readonly pageIndex?: number;
  readonly pageSize?: number;
  readonly totalItems?: number;
  readonly totalPages?: number;
}
