/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface UpdatePersonRequest {
  /** @nullable */
  apelido?: string | null;
  ativo?: boolean;
  /** @nullable */
  cpfCnpj?: string | null;
  fisJur: number;
  /** @nullable */
  fundacao?: string | null;
  id?: string;
  /** @nullable */
  idAlternativo?: string | null;
  /** @nullable */
  identidade?: string | null;
  /** @nullable */
  identidadeEmissor?: string | null;
  /** @nullable */
  inscricaoEstadual?: string | null;
  /** @nullable */
  inscricaoMunicipal?: string | null;
  /** @nullable */
  inscricaoProdutorRural?: string | null;
  /** @nullable */
  inscricaoSuFrama?: string | null;
  /** @nullable */
  nascimento?: string | null;
  /** @nullable */
  nome: string | null;
  /** @nullable */
  observacao?: string | null;
  /** @nullable */
  site?: string | null;
}
