/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */
import type { TenantDto } from './tenantDto';

export interface UserLoginResponse {
  /** @nullable */
  email?: string | null;
  emailConfirmed?: boolean;
  /** @nullable */
  firstName?: string | null;
  id?: string;
  /** @nullable */
  imageUrl?: string | null;
  isActive?: boolean;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  tenantId?: string | null;
  /** @nullable */
  tenants?: TenantDto[] | null;
  /** @nullable */
  userName?: string | null;
}
