/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */
import type { UserDetailsDto } from './userDetailsDto';

export interface UserDetailsDtoIPagedList {
  readonly hasNext?: boolean;
  readonly hasPrevious?: boolean;
  /** @nullable */
  readonly items?: readonly UserDetailsDto[] | null;
  readonly pageIndex?: number;
  readonly pageSize?: number;
  readonly totalItems?: number;
  readonly totalPages?: number;
}
