/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface UserTenantCreateUpdateRequest {
  adminUser?: number;
  isActive?: boolean;
  /** @nullable */
  tenantId: string | null;
  /** @nullable */
  userId: string | null;
}
