/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface UserRoleDto {
  /** @nullable */
  description?: string | null;
  enabled?: boolean;
  /** @nullable */
  roleId?: string | null;
  /** @nullable */
  roleName?: string | null;
}
