/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export type AtualizarUsuárioParaTenantParams = {
/**
 * Id do usuário para alteração
 */
userId: string;
};
