/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export type ConfirmarEMailParams = {
/**
 * Id do usuário.
 */
userId: string;
/**
 * Código verificação para o e-mail.
 */
code: string;
};
