/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export type ObterPermissõesDoUsuárioPorIdParams = {
/**
 * ID do Usuário
 */
userId: string;
/**
 * Tenant ao qual o usuário pertence
 */
tenantId: string;
};
