/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface PersonResponse {
  /** @nullable */
  apelido?: string | null;
  ativo?: boolean;
  /** @nullable */
  cpfCnpj?: string | null;
  createdOn?: string;
  fisJur?: number;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  idAlternativo?: string | null;
  /** @nullable */
  identidade?: string | null;
  /** @nullable */
  identidadeEmissor?: string | null;
  /** @nullable */
  inscricaoEstadual?: string | null;
  /** @nullable */
  inscricaoMunicipal?: string | null;
  /** @nullable */
  inscricaoProdutorRural?: string | null;
  /** @nullable */
  inscricaoSuFrama?: string | null;
  /** @nullable */
  nascimentoFundacao?: string | null;
  /** @nullable */
  nome: string | null;
  /** @nullable */
  observacao?: string | null;
  /** @nullable */
  site?: string | null;
}
