/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface TenantStrConnResponse {
  /** @nullable */
  connStringBasicRecords?: string | null;
  /** @nullable */
  connStringCepRecords?: string | null;
  /** @nullable */
  connStringProductsBasic?: string | null;
  /** @nullable */
  connStringTenant?: string | null;
  /** @nullable */
  schemaName?: string | null;
}
