/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface TenantsLicenseDto {
  ativo?: boolean;
  demonstracao?: number;
  /** @nullable */
  funcionalidade?: string | null;
  id?: string;
  /** @nullable */
  licenseKey?: string | null;
  /** @nullable */
  tenantId?: string | null;
  validoAte?: string;
}
