/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */

export interface TokenResponse {
  /** @nullable */
  refreshToken?: string | null;
  refreshTokenExpiryTime?: string;
  /** @nullable */
  token?: string | null;
}
