/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */
import type {
  AlterarStatusDoUsuárioParams,
  AtualizarUsuárioParaTenantParams,
  ConfirmarEMailParams,
  ConfirmarTelefoneParams,
  CreateUserRequest,
  ForgotPasswordRequest,
  ObterListaDePerfisParams,
  ObterListaDeUsuáriosParams,
  ObterPermissõesDoUsuárioPorIdParams,
  ObterUsuárioPorIdParams,
  ResetPasswordRequest,
  ToggleUserStatusRequest,
  UserDetailsDto,
  UserDetailsDtoIPagedList,
  UserLoginRequest,
  UserLoginResponse,
  UserRoleDto,
  UserTenantCreateUpdateRequest
} from '../../interfaces/api'
import { customInstance } from '../../api/api-interceptor';
import type { BodyType } from '../../api/api-interceptor';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  export const getUsers = () => {
/**
 * @summary Loga usuário fornecendo lista de tenants que usuário tem acesso.
 */
const loginUsuário = (
    userLoginRequest: BodyType<UserLoginRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<UserLoginResponse>(
      {url: `/api/user/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLoginRequest
    },
      options);
    }
  /**
 * @summary Confirma e-mail do usuário através de código.
 */
const confirmarEMail = (
    params: ConfirmarEMailParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/confirm-email`, method: 'POST',
        params
    },
      options);
    }
  /**
 * @summary Confirma telefone do usuário através de código.
 */
const confirmarTelefone = (
    params: ConfirmarTelefoneParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/confirm-phone-number`, method: 'POST',
        params
    },
      options);
    }
  /**
 * @summary Solicitação de redefinição de senha.
 */
const esqueciMinhaSenha = (
    forgotPasswordRequest: BodyType<ForgotPasswordRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordRequest
    },
      options);
    }
  /**
 * @summary Redefinição de senha.
 */
const redefinirSenha = (
    resetPasswordRequest: BodyType<ResetPasswordRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequest
    },
      options);
    }
  /**
 * @summary Localiza usuário por Id.
 */
const obterUsuárioPorId = (
    params: ObterUsuárioPorIdParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<UserDetailsDto>(
      {url: `/api/user/id`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Lista todos os usuários cadastrados.
 */
const obterListaDeUsuários = (
    params?: ObterListaDeUsuáriosParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<UserDetailsDtoIPagedList>(
      {url: `/api/user/all`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Lista todos os perfis cadastrados.
 */
const obterListaDePerfis = (
    params: ObterListaDePerfisParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<UserRoleDto[]>(
      {url: `/api/user/roles`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Cria um novo usuário.
 */
const criarUsuário = (
    createUserRequest: BodyType<CreateUserRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest
    },
      options);
    }
  /**
 * @summary Cria um novo usuário, na api identidade e na base do tenant.
 */
const criarUsuárioNoTenant = (
    createUserRequest: BodyType<CreateUserRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/create-in-tenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest
    },
      options);
    }
  /**
 * @summary Localiza permissões do usuário por Id.
 */
const obterPermissõesDoUsuárioPorId = (
    params: ObterPermissõesDoUsuárioPorIdParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string[]>(
      {url: `/api/user/permissions`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Ativa ou desativa um usuário.
 */
const alterarStatusDoUsuário = (
    toggleUserStatusRequest: BodyType<ToggleUserStatusRequest>,
    params: AlterarStatusDoUsuárioParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/toggle-status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: toggleUserStatusRequest,
        params
    },
      options);
    }
  /**
 * @summary Cria um usuário para os tenants especificados.
 */
const criarUsuárioParaTenant = (
    userTenantCreateUpdateRequest: BodyType<UserTenantCreateUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/create-user-tenant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userTenantCreateUpdateRequest
    },
      options);
    }
  /**
 * @summary Atualiza um usuário para os tenants especificados.
 */
const atualizarUsuárioParaTenant = (
    userTenantCreateUpdateRequest: BodyType<UserTenantCreateUpdateRequest>,
    params: AtualizarUsuárioParaTenantParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/user/update-user-tenant`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userTenantCreateUpdateRequest,
        params
    },
      options);
    }
  return {loginUsuário,confirmarEMail,confirmarTelefone,esqueciMinhaSenha,redefinirSenha,obterUsuárioPorId,obterListaDeUsuários,obterListaDePerfis,criarUsuário,criarUsuárioNoTenant,obterPermissõesDoUsuárioPorId,alterarStatusDoUsuário,criarUsuárioParaTenant,atualizarUsuárioParaTenant}};
export type LoginUsuárioResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['loginUsuário']>>>
export type ConfirmarEMailResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['confirmarEMail']>>>
export type ConfirmarTelefoneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['confirmarTelefone']>>>
export type EsqueciMinhaSenhaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['esqueciMinhaSenha']>>>
export type RedefinirSenhaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['redefinirSenha']>>>
export type ObterUsuárioPorIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['obterUsuárioPorId']>>>
export type ObterListaDeUsuáriosResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['obterListaDeUsuários']>>>
export type ObterListaDePerfisResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['obterListaDePerfis']>>>
export type CriarUsuárioResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['criarUsuário']>>>
export type CriarUsuárioNoTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['criarUsuárioNoTenant']>>>
export type ObterPermissõesDoUsuárioPorIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['obterPermissõesDoUsuárioPorId']>>>
export type AlterarStatusDoUsuárioResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['alterarStatusDoUsuário']>>>
export type CriarUsuárioParaTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['criarUsuárioParaTenant']>>>
export type AtualizarUsuárioParaTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['atualizarUsuárioParaTenant']>>>
