/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0
 */
import type {
  AtivarTenantParams,
  CreateTenantRequest,
  DesativarTenantParams,
  ObterListaDeTenantsParams,
  ObterStringDeConexãoDoTenantParams,
  ObterTenantPorIdParams,
  ObterTenantsPorGrupoParams,
  TenantDto,
  TenantDtoIPagedList,
  TenantGroupDto,
  TenantStrConnResponse
} from '../../interfaces/api'
import { customInstance } from '../../api/api-interceptor';
import type { BodyType } from '../../api/api-interceptor';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  export const getTenants = () => {
/**
 * @summary Lista todos os tenants cadastrados.
 */
const obterListaDeTenants = (
    params?: ObterListaDeTenantsParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TenantDtoIPagedList>(
      {url: `/api/tenant/all`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Obtém um tenant pelo id.
 */
const obterTenantPorId = (
    params: ObterTenantPorIdParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TenantDto>(
      {url: `/api/tenant/id`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Obtém todos os tenants de um grupo.
 */
const obterTenantsPorGrupo = (
    params: ObterTenantsPorGrupoParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TenantDto[]>(
      {url: `/api/tenant/by-group`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Obtém todos os grupos de tenants.
 */
const obterTodosOsGruposDeTenants = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TenantGroupDto[]>(
      {url: `/api/tenant/all-groups`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Cria um novo tenant.
 */
const criarTenant = (
    createTenantRequest: BodyType<CreateTenantRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/tenant/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTenantRequest
    },
      options);
    }
  /**
 * @summary Ativa um tenant.
 */
const ativarTenant = (
    params: AtivarTenantParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/tenant/activate`, method: 'PUT',
        params
    },
      options);
    }
  /**
 * @summary Desativa um tenant.
 */
const desativarTenant = (
    params: DesativarTenantParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/tenant/deactivate`, method: 'PUT',
        params
    },
      options);
    }
  /**
 * @summary Obtém a string de conexão do tenant.
 */
const obterStringDeConexãoDoTenant = (
    params: ObterStringDeConexãoDoTenantParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<TenantStrConnResponse>(
      {url: `/api/tenant/get-connectionstring`, method: 'GET',
        params
    },
      options);
    }
  return {obterListaDeTenants,obterTenantPorId,obterTenantsPorGrupo,obterTodosOsGruposDeTenants,criarTenant,ativarTenant,desativarTenant,obterStringDeConexãoDoTenant}};
export type ObterListaDeTenantsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['obterListaDeTenants']>>>
export type ObterTenantPorIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['obterTenantPorId']>>>
export type ObterTenantsPorGrupoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['obterTenantsPorGrupo']>>>
export type ObterTodosOsGruposDeTenantsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['obterTodosOsGruposDeTenants']>>>
export type CriarTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['criarTenant']>>>
export type AtivarTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['ativarTenant']>>>
export type DesativarTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['desativarTenant']>>>
export type ObterStringDeConexãoDoTenantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTenants>['obterStringDeConexãoDoTenant']>>>
